apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-gcp-credentials
  labels:
    {{- include "instrument-classification-retrain-api.labels" . | nindent 4 }}
spec:
  podIdentity:
    provider: gcp
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "instrument-classification-retrain-api.fullname" . }}
  labels:
    {{- include "instrument-classification-retrain-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "instrument-classification-retrain-api.fullname" . }}
  minReplicaCount: {{ .Values.scaledObject.minReplicaCount }}
  maxReplicaCount: {{ .Values.scaledObject.maxReplicaCount }}
  triggers:
    - type: gcp-pubsub
      authenticationRef:
        name: keda-trigger-auth-gcp-credentials
      metadata:
        mode: "SubscriptionSize"
        value: {{ .Values.scaledObject.slotCount | quote }}
        subscriptionName: {{ .Values.scaledObject.subscriptionName | quote }}